### ISSUE TITLE
Code screenshot suggests false || true returns false

### ISSUE THREAD

**Issue by wtennis** [learn-co-curriculum/phase-3-control-flow-operators#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/4214/pages/control-flow-operators?module_item_id=281431

## What should be changed?
Code picture underneath "Logical Operators" heading 

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

false || true returns true in Ruby

## Additional context
![Screen Shot 2021-08-08 at 10 24 14 AM](https://user-images.githubusercontent.com/79941126/128642020-bd43d1d0-3702-440e-a6c3-85a409cba09a.png)

**Comment by graciemcguire** [comment]
Hello,

We've created a pull request for this issue, and merged it in. Thank you for submitting this issue and for contributing to a learn-co-curriculum repository!

We appreciate your support! 💙
