### ISSUE TITLE
Typos to be corrected

### ISSUE THREAD

**Issue by madisonsorah** [learn-co-curriculum/phase-3-control-flow-operators#4]
1. That means that in order to use control flow effectively, it's important **to be know how** to use conditional operators to compare values. Change to **to know how**
 
2. Because **Ruby is heavily favors** object-orientation as a language, you'll find that many features other languages would define as operators (like ==, >, even math operators like + and *) are actually methods. Change to **Ruby heavily favors**

**Comment by lizbur10** [comment]
Fixed! Thanks again, @madisonsorah ! 💙
